//
// Generated file, do not edit! Created by nedtool 5.5 from OnuSdu.msg.
//

#ifndef __ONUSDU_M_H
#define __ONUSDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>OnuSdu.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet OnuSdu
 * {
 *     int serialNumber;
 *     int allocId;
 *     simtime_t insertionTime;
 *     int64_t originalByteLength;
 * }
 * </pre>
 */
class OnuSdu : public ::omnetpp::cPacket
{
  protected:
    int serialNumber;
    int allocId;
    ::omnetpp::simtime_t insertionTime;
    int64_t originalByteLength;

  private:
    void copy(const OnuSdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OnuSdu&);

  public:
    OnuSdu(const char *name=nullptr, short kind=0);
    OnuSdu(const OnuSdu& other);
    virtual ~OnuSdu();
    OnuSdu& operator=(const OnuSdu& other);
    virtual OnuSdu *dup() const override {return new OnuSdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSerialNumber() const;
    virtual void setSerialNumber(int serialNumber);
    virtual int getAllocId() const;
    virtual void setAllocId(int allocId);
    virtual ::omnetpp::simtime_t getInsertionTime() const;
    virtual void setInsertionTime(::omnetpp::simtime_t insertionTime);
    virtual int64_t getOriginalByteLength() const;
    virtual void setOriginalByteLength(int64_t originalByteLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OnuSdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OnuSdu& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ONUSDU_M_H

